package main

import "fmt"

// moviePool intentionally exceeds 2500+ entries for varied multiplayer rounds.
var moviePool = buildMoviePool()

func buildMoviePool() []string {
	base := []string{
		// Original List
		"Sholay", "Mughal E Azam", "Mother India", "Guide", "Pyaasa", "Deewar", "Anand", "Amar Akbar Anthony",
		"Don", "Karz", "Qayamat Se Qayamat Tak", "Maine Pyar Kiya", "Jo Jeeta Wohi Sikandar", "Hum Aapke Hain Koun",
		"Andaz Apna Apna", "Dilwale Dulhania Le Jayenge", "Rangeela", "Raja Hindustani", "Border", "Kuch Kuch Hota Hai",
		"Satya", "Sarfarosh", "Hum Dil De Chuke Sanam", "Lagaan", "Dil Chahta Hai", "Devdas", "Kal Ho Naa Ho",
		"Munna Bhai M B B S", "Swades", "Veer Zaara", "Black", "Rang De Basanti", "Lage Raho Munna Bhai", "Don 2",
		"Om Shanti Om", "Taare Zameen Par", "Jab We Met", "A Wednesday", "Ghajini", "3 Idiots", "My Name Is Khan",
		"Dabangg", "Zindagi Na Milegi Dobara", "Rockstar", "The Dirty Picture", "Kahaani", "Gangs of Wasseypur",
		"Barfi", "English Vinglish", "Bhaag Milkha Bhaag", "Queen", "Haider", "PK", "Piku", "Bajrangi Bhaijaan",
		"Baahubali", "Neerja", "Kapoor and Sons", "Dangal", "Pink", "Hindi Medium", "Bareilly Ki Barfi",
		"Secret Superstar", "Andhadhun", "Raazi", "Gully Boy", "Article 15", "Chhichhore", "Uri",
		"Shubh Mangal Zyada Saavdhan", "Ludo", "Sherni", "Sardar Udham", "Shershaah", "Gangubai Kathiawadi",
		"Bhool Bhulaiyaa", "Bhool Bhulaiyaa 2", "Drishyam", "Drishyam 2", "RRR", "Pathaan", "Jawan", "Animal",
		"12th Fail", "Laapataa Ladies", "Stree", "Stree 2", "Madgaon Express", "Crew", "Rocky Aur Rani Kii Prem Kahaani",
		"Brahmastra", "Yeh Jawaani Hai Deewani", "Kesari", "Tanhaji", "Kabir Singh", "Padmaavat", "Pad Man",
		"Sonu Ke Titu Ki Sweety", "Baahubali The Beginning", "Baahubali 2 The Conclusion", "KGF Chapter 1", "KGF Chapter 2",
		"Pushpa The Rise", "Pushpa 2", "Kantara", "Jailer", "Leo", "Vikram", "Master", "Kaithi", "96", "Asuran",
		"Soorarai Pottru", "Jigarthanda", "Minnal Murali", "Premam", "Bangalore Days", "Lucifer", "Ustad Hotel",
		"Drishyam Malayalam", "Charlie", "Super Deluxe", "Vada Chennai", "Aruvi", "Mahanati", "Eega", "Jersey",
		"Arjun Reddy", "Sita Ramam", "Hanu Man", "Salaar", "Kalki 2898 AD", "The Shawshank Redemption", "The Godfather",
		"The Godfather Part II", "The Dark Knight", "Pulp Fiction", "Fight Club", "Forrest Gump", "The Matrix",
		"Inception", "Interstellar", "Memento", "Dunkirk", "Oppenheimer", "The Prestige", "Tenet", "The Departed",
		"Goodfellas", "Casino", "The Irishman", "Taxi Driver", "Raging Bull", "The Wolf of Wall Street",
		"Killers of the Flower Moon", "Schindlers List", "Saving Private Ryan", "Jurassic Park", "Jaws",
		"E T The Extra Terrestrial", "Close Encounters of the Third Kind", "Raiders of the Lost Ark",
		"Indiana Jones and the Last Crusade", "Indiana Jones and the Temple of Doom", "The Last Samurai", "Top Gun",
		"Top Gun Maverick", "Mission Impossible", "Minority Report", "Edge of Tomorrow", "The Color of Money",
		"Rain Man", "Titanic", "Avatar", "Avatar The Way of Water", "Terminator", "Terminator 2 Judgment Day",
		"Aliens", "Alien", "Gladiator", "Oceans 11", "Blade Runner", "Blade Runner 2049", "The Martian",
		"Thelma and Louise", "American Gangster", "Training Day", "Remember the Titans", "Cast Away", "Philadelphia",
		"The Green Mile", "Se7en", "Gone Girl", "Zodiac", "The Social Network", "The Curious Case Of Benjamin Button",
		"The Silence of the Lambs", "Hannibal", "No Country For Old Men", "Fargo", "There Will Be Blood",
		"The Big Lebowski", "A Serious Man", "The Grand Budapest Hotel", "Fantastic Mr Fox", "Moonrise Kingdom",
		"Whiplash", "La La Land", "Babylon", "Mad Max Fury Road", "Furiosa", "Logan", "Deadpool", "Deadpool 2",
		"Deadpool and Wolverine", "X Men", "X2", "X Men First Class", "Days of Future Past", "The Avengers",
		"Avengers Age of Ultron", "Avengers Infinity War", "Avengers Endgame", "Iron Man", "Iron Man 2", "Iron Man 3",
		"Captain America The First Avenger", "Captain America The Winter Soldier", "Captain America Civil War", "Thor",
		"Thor Ragnarok", "Thor Love and Thunder", "Black Panther", "Black Panther Wakanda Forever", "Doctor Strange",
		"Doctor Strange in the Multiverse of Madness", "Spider Man", "Spider Man 2", "Spider Man 3",
		"The Amazing Spider Man", "The Amazing Spider Man 2", "Spider Man Homecoming", "Spider Man Far From Home",
		"Spider Man No Way Home", "The Batman", "Batman Begins", "The Dark Knight Rises", "Man of Steel",
		"Wonder Woman", "Aquaman", "Joker", "Suicide Squad", "The Suicide Squad", "Dune", "Dune Part Two",
		"Arrival", "Sicario", "Prisoners", "Blade", "Rocky", "Rambo", "First Blood", "Creed", "Creed II", "Creed III",
		"John Wick", "John Wick Chapter 2", "John Wick Chapter 3 Parabellum", "John Wick Chapter 4", "The Hunger Games",
		"Catching Fire", "Mockingjay", "Harry Potter and the Sorcerers Stone", "Harry Potter and the Chamber of Secrets",
		"Harry Potter and the Prisoner of Azkaban", "Harry Potter and the Goblet of Fire",
		"Harry Potter and the Order of the Phoenix", "Harry Potter and the Half Blood Prince",
		"Harry Potter and the Deathly Hallows", "Fantastic Beasts and Where to Find Them",
		"The Lord of the Rings The Fellowship of the Ring", "The Lord of the Rings The Two Towers",
		"The Lord of the Rings The Return of the King", "The Hobbit An Unexpected Journey",
		"The Hobbit The Desolation of Smaug", "The Hobbit The Battle of the Five Armies", "Star Wars A New Hope",
		"The Empire Strikes Back", "Return of the Jedi", "The Phantom Menace", "Attack of the Clones",
		"Revenge of the Sith", "The Force Awakens", "The Last Jedi", "The Rise of Skywalker", "Rogue One",
		"Solo A Star Wars Story", "Toy Story", "Toy Story 2", "Toy Story 3", "Toy Story 4", "Up", "Inside Out",
		"Inside Out 2", "Coco", "Finding Nemo", "Finding Dory", "The Incredibles", "Incredibles 2", "Monsters Inc",
		"Monsters University", "Cars", "Cars 2", "Cars 3", "Ratatouille", "WALL E", "Soul", "Luca", "Turning Red",
		"Elemental", "Moana", "Frozen", "Frozen II", "Encanto", "The Lion King", "Aladdin", "Beauty and the Beast",
		"Mulan", "The Little Mermaid", "The Jungle Book", "Cinderella", "Pinocchio", "Bambi", "The Notebook",
		"A Star Is Born", "Notting Hill", "Pretty Woman", "The Devil Wears Prada", "Legally Blonde", "Mean Girls",
		"Clueless", "Crazy Rich Asians", "Knives Out", "Glass Onion", "The Holdovers", "Barbie", "Little Women",
		"Lady Bird", "Room", "Her", "Ex Machina", "Annihilation", "Black Swan", "Birdman", "The Revenant",
		"The Hateful Eight", "Inglourious Basterds", "Django Unchained", "Once Upon a Time in Hollywood",
		"The Imitation Game", "The Theory of Everything", "Bohemian Rhapsody", "Elvis", "Rocketman", "A Beautiful Mind",
		"The Pianist", "Amadeus", "The Truman Show", "Groundhog Day", "The Sixth Sense", "Unbreakable", "Split",
		"Glass", "Nightcrawler", "Donnie Darko",

		// --- HOLLYWOOD EXPANSION ---
		"12 Angry Men", "One Flew Over the Cuckoos Nest", "Good Will Hunting", "City of God", "Life Is Beautiful", "Seven Samurai", "Its a Wonderful Life", "Spirited Away", "Parasite", "Leon The Professional", "The Usual Suspects", "The Lion King", "American History X", "The Intouchables", "Casablanca", "Rear Window", "Cinema Paradiso", "Modern Times", "City Lights", "Grave of the Fireflies", "Apocalypse Now", "Memento", "Raiders of the Lost Ark", "Django Unchained", "WALL E", "The Lives of Others", "Sunset Boulevard", "Paths of Glory", "The Shining", "The Great Dictator", "Witness for the Prosecution", "Aliens", "American Beauty", "The Dark Knight Rises", "Oldboy", "Amelie", "Braveheart", "Toy Story", "Coco", "Das Boot", "Inglourious Basterds", "Princess Mononoke", "Once Upon a Time in America", "Good Will Hunting", "Requiem for a Dream", "Toy Story 3", "Your Name", "Singin in the Rain", "3 Idiots", "Star Wars Return of the Jedi", "2001 A Space Odyssey", "High and Low", "Capernaum", "Reservoir Dogs", "The Hunt", "Come and See", "Goodfellas", "Seven", "City of God", "The Silence of the Lambs", "Its a Wonderful Life", "Life Is Beautiful", "Spirited Away", "Parasite", "Interstellar", "The Green Mile", "Grave of the Fireflies", "Psycho", "The Pianist", "The Terminator", "Terminator 2", "Back to the Future", "Back to the Future Part II", "Back to the Future Part III", "Alien", "Aliens", "The Thing", "Die Hard", "Die Hard 2", "Die Hard with a Vengeance", "Lethal Weapon", "Lethal Weapon 2", "Lethal Weapon 3", "Lethal Weapon 4", "The Matrix Reloaded", "The Matrix Revolutions", "The Matrix Resurrections", "John Wick", "John Wick 2", "Mad Max", "The Road Warrior", "Mad Max Beyond Thunderdome", "Fury Road", "Labyrinth", "The Dark Crystal", "The NeverEnding Story", "The Princess Bride", "Willow", "E T the Extra Terrestrial", "Jurassic Park", "The Lost World", "Jurassic Park III", "Jurassic World", "Jurassic World Fallen Kingdom", "Jurassic World Dominion", "King Kong", "Godzilla", "Pacific Rim", "Cloverfield", "Super 8", "Transformers", "Revenge of the Fallen", "Dark of the Moon", "Age of Extinction", "The Last Knight", "Bumblebee", "Rise of the Beasts", "Pirates of the Caribbean", "The Curse of the Black Pearl", "Dead Mans Chest", "At Worlds End", "On Stranger Tides", "Dead Men Tell No Tales", "National Treasure", "National Treasure Book of Secrets", "The Mummy", "The Mummy Returns", "Tomb Raider", "Lara Croft Tomb Raider", "Uncharted", "Assassins Creed", "Resident Evil", "Silent Hill", "Mortal Kombat", "Street Fighter", "Super Mario Bros", "Sonic the Hedgehog", "Sonic the Hedgehog 2", "Detective Pikachu", "The Super Mario Bros Movie", "Spider Man Into the Spider Verse", "Spider Man Across the Spider Verse", "Venom", "Venom Let There Be Carnage", "Morbius", "Madame Web", "Kraven the Hunter", "Deadpool", "Deadpool 2", "Logan", "X Men", "X2", "The Last Stand", "First Class", "Days of Future Past", "Apocalypse", "Dark Phoenix", "The New Mutants", "Fantastic Four", "Rise of the Silver Surfer", "Blade", "Blade II", "Blade Trinity", "Ghost Rider", "Spirit of Vengeance", "Daredevil", "Elektra", "Punisher", "Punisher War Zone", "Hulk", "The Incredible Hulk", "Iron Man", "Captain America", "Thor", "Avengers", "Guardians of the Galaxy", "Ant Man", "Doctor Strange", "Black Panther", "Captain Marvel", "Black Widow", "Shang Chi", "Eternals", "Superman", "Superman II", "Superman Returns", "Man of Steel", "Batman", "Batman Returns", "Batman Forever", "Batman and Robin", "Batman Begins", "The Dark Knight", "The Dark Knight Rises", "Batman v Superman", "Justice League", "Zack Snyders Justice League", "Wonder Woman", "Wonder Woman 1984", "Aquaman", "Aquaman and the Lost Kingdom", "The Flash", "Shazam", "Shazam Fury of the Gods", "Black Adam", "Suicide Squad", "The Suicide Squad", "Peacemaker", "Joker", "Joker Folie a Deux", "V for Vendetta", "Watchmen", "Constantine", "The League of Extraordinary Gentlemen", "Hellboy", "Hellboy II The Golden Army", "Sin City", "300", "300 Rise of an Empire", "Kick Ass", "Kick Ass 2", "Kingsman The Secret Service", "Kingsman The Golden Circle", "The Kings Man", "Wanted", "Scott Pilgrim vs the World", "Snowpiercer", "Alita Battle Angel", "Ghost in the Shell", "Akira", "Spirited Away", "My Neighbor Totoro", "Howls Moving Castle", "Ponyo", "Kikis Delivery Service", "Princess Mononoke", "The Wind Rises", "Weathering with You", "Your Name", "Suzume", "A Silent Voice", "Demon Slayer Mugen Train", "Jujutsu Kaisen 0", "Dragon Ball Super Broly", "Dragon Ball Super Super Hero", "Naruto The Movie", "One Piece Film Red", "Pokemon The First Movie", "The Lion King", "Beauty and the Beast", "Aladdin", "Mulan", "Pocahontas", "Tarzan", "Hercules", "The Hunchback of Notre Dame", "The Little Mermaid", "Cinderella", "Snow White and the Seven Dwarfs", "Sleeping Beauty", "Peter Pan", "Alice in Wonderland", "The Jungle Book", "101 Dalmatians", "Robin Hood", "The Aristocats", "The Rescuers", "The Fox and the Hound", "The Black Cauldron", "The Great Mouse Detective", "Oliver and Company", "The Rescuers Down Under", "A Goofy Movie", "Toy Story", "A Bugs Life", "Toy Story 2", "Monsters Inc", "Finding Nemo", "The Incredibles", "Cars", "Ratatouille", "WALL E", "Up", "Toy Story 3", "Cars 2", "Brave", "Monsters University", "Inside Out", "The Good Dinosaur", "Finding Dory", "Cars 3", "Coco", "Incredibles 2", "Toy Story 4", "Onward", "Soul", "Luca", "Turning Red", "Lightyear", "Elemental", "Shrek", "Shrek 2", "Shrek the Third", "Shrek Forever After", "Puss in Boots", "Puss in Boots The Last Wish", "Madagascar", "Madagascar Escape 2 Africa", "Madagascar 3 Europes Most Wanted", "Penguins of Madagascar", "Kung Fu Panda", "Kung Fu Panda 2", "Kung Fu Panda 3", "Kung Fu Panda 4", "How to Train Your Dragon", "How to Train Your Dragon 2", "How to Train Your Dragon The Hidden World", "Megamind", "Monsters vs Aliens", "The Croods", "The Croods A New Age", "Trolls", "Trolls World Tour", "Trolls Band Together", "The Boss Baby", "The Boss Baby Family Business", "Despicable Me", "Despicable Me 2", "Despicable Me 3", "Despicable Me 4", "Minions", "Minions The Rise of Gru", "The Secret Life of Pets", "The Secret Life of Pets 2", "Sing", "Sing 2", "Ice Age", "Ice Age The Meltdown", "Ice Age Dawn of the Dinosaurs", "Ice Age Continental Drift", "Ice Age Collision Course", "Rio", "Rio 2", "Ferdinand", "Spies in Disguise", "The Peanuts Movie", "Horton Hears a Who", "Robots", "Epic", "Coraline", "ParaNorman", "The Boxtrolls", "Kubo and the Two Strings", "Missing Link", "The Nightmare Before Christmas", "Corpse Bride", "Frankenweenie", "James and the Giant Peach", "Fantastic Mr Fox", "Isle of Dogs", "Wallace and Gromit", "Chicken Run", "Flushed Away", "Arthur Christmas", "The Pirates Band of Misfits", "Shaun the Sheep Movie", "Early Man", "Spider Man Into the Spider Verse", "Spider Man Across the Spider Verse", "The Mitchells vs the Machines", "Cloudy with a Chance of Meatballs", "Hotel Transylvania", "The Smurfs", "The Emoji Movie", "Peter Rabbit", "Paddington", "Paddington 2", "Sonic the Hedgehog", "The Lego Movie", "The Lego Batman Movie", "The Lego Ninjago Movie", "The Lego Movie 2 The Second Part", "Harry Potter", "Fantastic Beasts", "The Lord of the Rings", "The Hobbit", "Star Wars", "Indiana Jones", "James Bond", "Mission Impossible", "Fast and Furious", "Transformers", "Pirates of the Caribbean", "Jurassic Park", "Marvel Cinematic Universe", "DC Extended Universe", "X Men", "Spider Man", "Batman", "Superman", "The Matrix", "Terminator", "Alien", "Predator", "Die Hard", "Lethal Weapon", "Rocky", "Rambo", "The Hunger Games", "Twilight", "Divergent", "Maze Runner", "Chronicles of Narnia", "Percy Jackson", "Planet of the Apes", "Godzilla", "King Kong", "Star Trek", "Men in Black", "Ghostbusters", "Back to the Future", "Mad Max", "Indiana Jones", "James Bond", "Fight Club", "Pulp Fiction", "Forrest Gump", "The Shawshank Redemption", "The Godfather", "The Dark Knight", "12 Angry Men", "Schindlers List", "The Lord of the Rings The Return of the King", "Goodfellas", "The Matrix", "Seven Samurai", "City of God", "Se7en", "The Silence of the Lambs", "Its a Wonderful Life", "Life Is Beautiful", "Spirited Away", "Saving Private Ryan", "Interstellar", "The Green Mile", "Parasite", "Leon The Professional", "The Usual Suspects", "The Lion King", "The Pianist", "Terminator 2 Judgment Day", "Back to the Future", "Modern Times", "Psycho", "Gladiator", "City Lights", "The Departed", "The Intouchables", "Whiplash", "The Prestige", "Grave of the Fireflies", "Once Upon a Time in the West", "Casablanca", "Cinema Paradiso", "Rear Window", "Alien", "Apocalypse Now", "Memento", "Raiders of the Lost Ark", "The Great Dictator", "Django Unchained", "The Lives of Others", "Paths of Glory", "Sunset Boulevard", "WALL E", "Avengers Infinity War", "Spider Man Into the Spider Verse", "The Shining", "Witness for the Prosecution", "Spider Man Across the Spider Verse", "Dr Strangelove", "The Dark Knight Rises", "Oldboy", "Aliens", "Amadeus", "Avengers Endgame", "Inglourious Basterds", "Coco", "Toy Story", "Braveheart", "Das Boot", "Princess Mononoke", "Good Will Hunting", "Once Upon a Time in America", "Requiem for a Dream", "Toy Story 3", "Your Name", "Singin in the Rain", "3 Idiots", "Star Wars Episode VI Return of the Jedi", "High and Low", "2001 A Space Odyssey", "Capernaum", "Reservoir Dogs", "The Hunt", "Come and See", "Goodfellas", "The Social Network", "The Wolf of Wall Street", "Mad Max Fury Road", "Inception", "Interstellar", "Dunkirk", "Tenet", "Oppenheimer", "The Grand Budapest Hotel", "Moonrise Kingdom", "Fantastic Mr Fox", "Isle of Dogs", "The French Dispatch", "Asteroid City", "Birdman", "The Revenant", "Gravity", "Roma", "Pan Labyrinth", "The Shape of Water", "Nightmare Alley", "Hellboy", "Blade Runner 2049", "Dune", "Dune Part Two", "Arrival", "Sicario", "Prisoners", "Enemy", "Incendies", "La La Land", "Whiplash", "First Man", "Babylon", "Get Out", "Us", "Nope", "Hereditary", "Midsommar", "Beau Is Afraid", "The Witch", "The Lighthouse", "The Northman", "Lady Bird", "Little Women", "Barbie", "Marriage Story", "Frances Ha", "The Squid and the Whale", "Boyhood", "Before Sunrise", "Before Sunset", "Before Midnight", "School of Rock", "Dazed and Confused", "Slumdog Millionaire", "Trainspotting", "28 Days Later", "Sunshine", "127 Hours", "Steve Jobs", "The Social Network", "Zodiac", "Gone Girl", "Se7en", "Fight Club", "The Curious Case of Benjamin Button", "Mank", "The Killer", "No Country for Old Men", "Fargo", "The Big Lebowski", "True Grit", "Inside Llewyn Davis", "O Brother Where Art Thou", "The Grand Budapest Hotel", "The French Dispatch", "Moonrise Kingdom", "Isle of Dogs", "Fantastic Mr Fox", "Asteroid City", "Pulp Fiction", "Reservoir Dogs", "Kill Bill", "Inglourious Basterds", "Django Unchained", "The Hateful Eight", "Once Upon a Time in Hollywood", "Jackie Brown", "Death Proof", "The Terminator", "Aliens", "Avatar", "Titanic", "The Abyss", "True Lies", "Avatar The Way of Water", "Jaws", "Close Encounters of the Third Kind", "Raiders of the Lost Ark", "E T the Extra Terrestrial", "Jurassic Park", "Schindlers List", "Saving Private Ryan", "Catch Me If You Can", "Minority Report", "War of the Worlds", "Lincoln", "Bridge of Spies", "Ready Player One", "West Side Story", "The Fabelmans", "Goodfellas", "Taxi Driver", "Raging Bull", "Casino", "The Departed", "The Wolf of Wall Street", "The Irishman", "Killers of the Flower Moon", "Gangs of New York", "The Aviator", "Shutter Island", "Hugo", "The Godfather", "Apocalypse Now", "The Conversation", "Dracula", "The Rainmaker", "The Outsiders", "Rumble Fish", "Peggy Sue Got Married", "Tucker The Man and His Dream", "The Godfather Part III", "The Godfather Part II", "The Shining", "2001 A Space Odyssey", "A Clockwork Orange", "Full Metal Jacket", "Eyes Wide Shut", "Dr Strangelove", "Barry Lyndon", "Lolita", "Paths of Glory", "Spartacus", "The Killing", "Fear and Loathing in Las Vegas", "Brazil", "12 Monkeys", "Time Bandits", "The Fisher King", "Monty Python and the Holy Grail", "Life of Brian", "The Meaning of Life", "The Princess Bride", "When Harry Met Sally", "Stand by Me", "Misery", "A Few Good Men", "The Bucket List", "Flipped", "Clueless", "Fast Times at Ridgemont High", "Jerry Maguire", "Almost Famous", "Say Anything", "Vanilla Sky", "We Bought a Zoo", "Aloha", "Elizabethtown", "Singles", "Boyhood", "Dazed and Confused", "School of Rock", "Before Sunrise", "Before Sunset", "Before Midnight", "Slacker", "Waking Life", "A Scanner Darkly", "Bernie", "Everybody Wants Some", "Last Flag Flying", "Whered You Go Bernadette", "Apollo 10 1/2", "Hit Man", "The Florida Project", "Tangerine", "Red Rocket", "Starlet", "Star Wars", "Empire Strikes Back", "Return of the Jedi", "The Phantom Menace", "Attack of the Clones", "Revenge of the Sith", "The Force Awakens", "The Last Jedi", "The Rise of Skywalker", "Rogue One", "Solo", "A New Hope", "The Matrix", "Matrix Reloaded", "Matrix Revolutions", "Matrix Resurrections", "John Wick", "John Wick Chapter 2", "John Wick Chapter 3", "John Wick Chapter 4", "Die Hard", "Die Hard 2", "Die Hard with a Vengeance", "Live Free or Die Hard", "A Good Day to Die Hard", "Lethal Weapon", "Lethal Weapon 2", "Lethal Weapon 3", "Lethal Weapon 4", "Terminator", "Terminator 2", "Terminator 3", "Terminator Salvation", "Terminator Genisys", "Terminator Dark Fate", "Alien", "Aliens", "Alien 3", "Alien Resurrection", "Prometheus", "Alien Covenant", "Predator", "Predator 2", "Predators", "The Predator", "Prey", "Alien vs Predator", "Aliens vs Predator Requiem", "RoboCop", "RoboCop 2", "RoboCop 3", "Mad Max", "The Road Warrior", "Mad Max Beyond Thunderdome", "Mad Max Fury Road", "Furiosa", "Ghostbusters", "Ghostbusters II", "Ghostbusters Answer the Call", "Ghostbusters Afterlife", "Ghostbusters Frozen Empire", "Back to the Future", "Back to the Future Part II", "Back to the Future Part III", "Indiana Jones and the Raiders of the Lost Ark", "Indiana Jones and the Temple of Doom", "Indiana Jones and the Last Crusade", "Indiana Jones and the Kingdom of the Crystal Skull", "Indiana Jones and the Dial of Destiny", "Jurassic Park", "The Lost World Jurassic Park", "Jurassic Park III", "Jurassic World", "Jurassic World Fallen Kingdom", "Jurassic World Dominion", "Harry Potter and the Sorcerers Stone", "Harry Potter and the Chamber of Secrets", "Harry Potter and the Prisoner of Azkaban", "Harry Potter and the Goblet of Fire", "Harry Potter and the Order of the Phoenix", "Harry Potter and the Half Blood Prince", "Harry Potter and the Deathly Hallows Part 1", "Harry Potter and the Deathly Hallows Part 2", "Fantastic Beasts and Where to Find Them", "Fantastic Beasts The Crimes of Grindelwald", "Fantastic Beasts The Secrets of Dumbledore", "The Lord of the Rings The Fellowship of the Ring", "The Lord of the Rings The Two Towers", "The Lord of the Rings The Return of the King", "The Hobbit An Unexpected Journey", "The Hobbit The Desolation of Smaug", "The Hobbit The Battle of the Five Armies", "Pirates of the Caribbean The Curse of the Black Pearl", "Pirates of the Caribbean Dead Mans Chest", "Pirates of the Caribbean At Worlds End", "Pirates of the Caribbean On Stranger Tides", "Pirates of the Caribbean Dead Men Tell No Tales", "Transformers", "Transformers Revenge of the Fallen", "Transformers Dark of the Moon", "Transformers Age of Extinction", "Transformers The Last Knight", "Bumblebee", "Transformers Rise of the Beasts", "Mission Impossible", "Mission Impossible II", "Mission Impossible III", "Mission Impossible Ghost Protocol", "Mission Impossible Rogue Nation", "Mission Impossible Fallout", "Mission Impossible Dead Reckoning Part One", "Fast and Furious", "2 Fast 2 Furious", "The Fast and the Furious Tokyo Drift", "Fast and Furious", "Fast Five", "Fast and Furious 6", "Furious 7", "The Fate of the Furious", "F9", "Fast X", "Hobbs and Shaw", "James Bond Dr No", "From Russia with Love", "Goldfinger", "Thunderball", "You Only Live Twice", "On Her Majestys Secret Service", "Diamonds Are Forever", "Live and Let Die", "The Man with the Golden Gun", "The Spy Who Loved Me", "Moonraker", "For Your Eyes Only", "Octopussy", "A View to a Kill", "The Living Daylights", "Licence to Kill", "GoldenEye", "Tomorrow Never Dies", "The World Is Not Enough", "Die Another Day", "Casino Royale", "Quantum of Solace", "Skyfall", "Spectre", "No Time to Die", "Never Say Never Again", "Awaara", "Shree 420", "Chalti Ka Naam Gaadi", "Kaagaz Ke Phool", "Padosan", "Aradhana", "Kati Patang", "Anand", "Chupke Chupke", "Gol Maal", "Bawarchi", "Mera Naam Joker", "Bobby", "Don", "Trishul", "Deewaar", "Zanjeer", "Kabhie Kabhie", "Silsila", "Kaala Patthar", "Namak Halaal", "Shaan", "Naseeb", "Lawaaris", "Muqaddar Ka Sikandar", "Karz", "Amar Akbar Anthony", "Dharam Veer", "Suhaag", "Mr Natwarlal", "Coolie", "Mard", "Himmatwala", "Tohfa", "Sadma", "Nagina", "Mr India", "Tezaab", "Ram Lakhan", "Parinda", "Beta", "Khalnayak", "Baazigar", "Darr", "Anjaam", "Karan Arjun", "Dilwale Dulhania Le Jayenge", "Kuch Kuch Hota Hai", "Dil To Pagal Hai", "Mohabbatein", "Kabhi Khushi Kabhie Gham", "Kal Ho Naa Ho", "Veer Zaara", "Kabhi Alvida Naa Kehna", "My Name Is Khan", "Student of the Year", "Hum Tum", "Salaam Namaste", "Fanaa", "Ta Ra Rum Pum", "Bachna Ae Haseeno", "Dostana", "Wake Up Sid", "Yeh Jawaani Hai Deewani", "Ae Dil Hai Mushkil", "Brahmastra", "Koi Mil Gaya", "Krrish", "Krrish 3", "Dhoom", "Dhoom 2", "Dhoom 3", "Ek Tha Tiger", "Tiger Zinda Hai", "Tiger 3", "War", "Pathaan", "Jawan", "Fighter", "Bang Bang", "Kaho Naa Pyaar Hai", "Gadar Ek Prem Katha", "Gadar 2", "Lagaan", "Dil Chahta Hai", "Swades", "Rang De Basanti", "Taare Zameen Par", "Ghajini", "3 Idiots", "PK", "Dangal", "Secret Superstar", "Thugs of Hindostan", "Laal Singh Chaddha", "Munna Bhai MBBS", "Lage Raho Munna Bhai", "Sanju", "Barfi", "Jagga Jasoos", "Animal", "Kabir Singh", "Arjun Reddy", "Bhool Bhulaiyaa", "Bhool Bhulaiyaa 2", "Hera Pheri", "Phir Hera Pheri", "Awara Paagal Deewana", "Deewane Huye Paagal", "Garam Masala", "Bhagam Bhag", "Welcome", "Welcome Back", "Singh Is Kinng", "Namastey London", "Heyy Babyy", "Housefull", "Housefull 2", "Housefull 3", "Housefull 4", "Golmaal", "Golmaal Returns", "Golmaal 3", "Golmaal Again", "Singham", "Singham Returns", "Simmba", "Sooryavanshi", "Chennai Express", "Happy New Year", "Dilwale", "Ra One", "Om Shanti Om", "Main Hoon Na", "Don The Chase Begins Again", "Don 2", "Zindagi Na Milegi Dobara", "Gully Boy", "Dil Dhadakne Do", "Talaash", "Rock On", "Lakshya", "Bhaag Milkha Bhaag", "Toofaan", "Mary Kom", "Paan Singh Tomar", "M S Dhoni The Untold Story", "Neerja", "Raazi", "Uri The Surgical Strike", "The Legend of Bhagat Singh", "Chak De India", "Airlift", "Baby", "Special 26", "A Wednesday", "Kahaani", "Andhadhun", "Badlapur", "Drishyam", "Drishyam 2", "Article 15", "Pink", "Thappad", "Piku", "Vicky Donor", "October", "Madras Cafe", "Sardar Udham", "Mimi", "Luka Chuppi", "Bareilly Ki Barfi", "Stree", "Bala", "Dream Girl", "Dream Girl 2", "Badhaai Ho", "Shubh Mangal Saavdhan", "Shubh Mangal Zyada Saavdhan", "Chandigarh Kare Aashiqui", "Doctor G", "An Action Hero", "Newton", "Stree", "Roohi", "Bhediya", "Munjya", "Stree 2", "Kalki 2898 AD", "Salaar", "Adipurush", "Radhe Shyam", "Saaho", "Baahubali", "Baahubali 2", "Pushpa", "Pushpa 2", "Rangasthalam", "Ala Vaikunthapurramuloo", "Arjun Reddy", "Geetha Govindam", "Dear Comrade", "Animal", "KGF Chapter 1", "KGF Chapter 2", "Kantara", "Vikrant Rona", "Charlie 777", "Master", "Leo", "Vikram", "Kaithi", "Roja", "Bombay", "Dil Se", "Guru", "Raavan", "Ponniyin Selvan I", "Ponniyin Selvan II", "Enthiran", "2 0", "Sivaji", "Kabali", "Kaala", "Petta", "Darbar", "Annaatthe", "Jailer", "Vada Chennai", "Asuran", "Karnan", "Super Deluxe", "Vikram Vedha", "Pariyerum Perumal", "Jai Bhim", "Soorarai Pottru", "Ratsasan", "96", "Premam", "Drishyam Malayalam", "Lucifer", "Kumbalangi Nights", "Bangalore Days", "Charlie", "Minnal Murali", "Jallikattu", "Hridayam", "Manjummel Boys", "Aavesham", "Premalu", "Bramayugam", "The Goat Life", "Kalki", "Devara", "Pushpa The Rule", "Indian 2", "Vidaa Muyarchi", "Kanguva", "Thangalaan", "GOAT", "Panchayat", "Mirzapur", "The Family Man", "Sacred Games", "Paatal Lok", "Scam 1992", "Farzi", "Asur", "Kota Factory", "Aarya", "Criminal Justice", "Delhi Crime", "Made in Heaven", "Gullak", "Aspirants", "Rocket Boys", "Maharani", "Half CA", "Yeh Meri Family", "Permanent Roommates", "TVF Pitchers", "Flames", "ImMature", "Hostel Daze", "Mismatched", "Little Things", "College Romance", "Guns and Gulaabs", "Kohrra", "Dahaad", "Jubilee", "Trial By Fire", "Scoop", "Churails", "Taj", "Heeramandi", "Panchayat Season 3", "Mirzapur Season 3", "The Family Man Season 3", "Gully Boy", "Gangs of Wasseypur Part 1", "Gangs of Wasseypur Part 2", "Udaan", "Dev D", "Black Friday", "Gulaal", "No Smoking", "Raman Raghav 2 0", "Mukkabaaz", "Lootera", "Trapped", "Bhavesh Joshi Superhero", "AK vs AK", "Monica O My Darling", "Mard Ko Dard Nahi Hota", "Khosla Ka Ghosla", "Oye Lucky Lucky Oye", "Love Sex Aur Dhokha", "Shanghai", "Detective Byomkesh Bakshy", "Sandeep Aur Pinky Faraar", "Ek Hasina Thi", "Johnny Gaddaar", "Agent Vinod", "Badlapur", "Andhadhun", "Merry Christmas", "Maqbool", "Omkara", "Kaminey", "7 Khoon Maaf", "Matru Ki Bijlee Ka Mandola", "Haider", "Rangoon", "Pataakha", "Khufiya", "Yahaan", "Vicky Donor", "Madras Cafe", "Piku", "Pink", "October", "Gulabo Sitabo", "Sardar Udham", "Luck By Chance", "Zindagi Na Milegi Dobara", "Dil Dhadakne Do", "Gully Boy", "The Archies", "Dil Chahta Hai", "Lakshya", "Don", "Don 2", "Jee Le Zaraa", "Kuch Kuch Hota Hai", "Kabhi Khushi Kabhie Gham", "Kabhi Alvida Naa Kehna", "My Name Is Khan", "Student of the Year", "Ae Dil Hai Mushkil", "Rocky Aur Rani Kii Prem Kahaani", "Khamoshi The Musical", "Hum Dil De Chuke Sanam", "Devdas", "Black", "Saawariya", "Guzaarish", "Goliyon Ki Raasleela Ram Leela", "Bajirao Mastani", "Padmaavat", "Gangubai Kathiawadi", "Heeramandi", "Munna Bhai M B B S", "Lage Raho Munna Bhai", "3 Idiots", "PK", "Sanju", "Dunki", "Qayamat Se Qayamat Tak", "Jo Jeeta Wohi Sikandar", "Andaz Apna Apna", "Rangeela", "Raja Hindustani", "Ishq", "Ghulam", "Sarfarosh", "Lagaan", "Dil Chahta Hai", "Rang De Basanti", "Fanaa", "Taare Zameen Par", "Ghajini", "3 Idiots", "Talaash", "Dhoom 3", "PK", "Dangal", "Secret Superstar", "Thugs of Hindostan", "Laal Singh Chaddha", "Sitaare Zameen Par", "Deewana", "Baazigar", "Darr", "Kabhi Haan Kabhi Naa", "Karan Arjun", "Dilwale Dulhania Le Jayenge", "Yes Boss", "Dil To Pagal Hai", "Kuch Kuch Hota Hai", "Mohabbatein", "Kabhi Khushi Kabhie Gham", "Devdas", "Kal Ho Naa Ho", "Main Hoon Na", "Veer Zaara", "Swades", "Don", "Chak De India", "Om Shanti Om", "Rab Ne Bana Di Jodi", "My Name Is Khan", "Ra One", "Don 2", "Jab Tak Hai Jaan", "Chennai Express", "Happy New Year", "Fan", "Raees", "Zero", "Pathaan", "Jawan", "Dunki", "King", "Maine Pyar Kiya", "Saajan", "Andaz Apna Apna", "Hum Aapke Hain Koun", "Karan Arjun", "Judwaa", "Pyar Kiya To Darna Kya", "Biwi No 1", "Hum Dil De Chuke Sanam", "Tere Naam", "Baghban", "Mujhse Shaadi Karogi", "No Entry", "Partner", "Wanted", "Dabangg", "Ready", "Bodyguard", "Ek Tha Tiger", "Dabangg 2", "Kick", "Bajrangi Bhaijaan", "Sultan", "Tiger Zinda Hai", "Race 3", "Bharat", "Dabangg 3", "Radhe", "Antim", "Kisi Ka Bhai Kisi Ki Jaan", "Tiger 3", "Sikandar", "Khiladi", "Mohra", "Main Khiladi Tu Anari", "Hera Pheri", "Dhadkan", "Ajnabee", "Aankhen", "Awara Paagal Deewana", "Mujhse Shaadi Karogi", "Garam Masala", "Phir Hera Pheri", "Bhagam Bhag", "Namastey London", "Heyy Babyy", "Bhool Bhulaiyaa", "Welcome", "Singh Is Kinng", "Housefull", "Rowdy Rathore", "OMG Oh My God", "Special 26", "Holiday", "Baby", "Airlift", "Rustom", "Jolly LLB 2", "Toilet Ek Prem Katha", "Pad Man", "Gold", "Kesari", "Mission Mangal", "Housefull 4", "Good Newwz", "Sooryavanshi", "Bell Bottom", "Raksha Bandhan", "Ram Setu", "OMG 2", "Mission Raniganj", "Bade Miyan Chote Miyan", "Sarfira", "Khel Khel Mein", "Kaho Naa Pyaar Hai", "Fiza", "Mission Kashmir", "Kabhi Khushi Kabhie Gham", "Koi Mil Gaya", "Lakshya", "Krrish", "Dhoom 2", "Jodhaa Akbar", "Guzaarish", "Zindagi Na Milegi Dobara", "Agneepath", "Krrish 3", "Bang Bang", "Mohenjo Daro", "Kaabil", "Super 30", "War", "Vikram Vedha", "Fighter", "War 2", "Saawariya", "Bachna Ae Haseeno", "Wake Up Sid", "Ajab Prem Ki Ghazab Kahani", "Rocket Singh", "Raajneeti", "Rockstar", "Barfi", "Yeh Jawaani Hai Deewani", "Tamasha", "Ae Dil Hai Mushkil", "Jagga Jasoos", "Sanju", "Brahmastra", "Tu Jhoothi Main Makkaar", "Animal", "Ramayana", "Love And War", "Band Baaja Baaraat", "Lootera", "Goliyon Ki Raasleela Ram Leela", "Gunday", "Dil Dhadakne Do", "Bajirao Mastani", "Padmaavat", "Simmba", "Gully Boy", "83", "Jayeshbhai Jordaar", "Cirkus", "Rocky Aur Rani Kii Prem Kahaani", "Singham Again", "Don 3", "Ishq Vishk", "Vivah", "Jab We Met", "Kaminey", "Haider", "Udta Punjab", "Padmaavat", "Kabir Singh", "Jersey", "Bloody Daddy", "Teri Baaton Mein Aisa Uljha Jiya", "Deva",
	}

	// Franchises will add hundreds more permutations procedurally
	franchises := map[string]int{
		"Fast and Furious":              11,
		"Mission Impossible":            10,
		"Rocky":                         8,
		"Rambo":                         5,
		"Scream":                        7,
		"Saw":                           10,
		"Final Destination":             5,
		"Paranormal Activity":           7,
		"The Conjuring":                 8,
		"Insidious":                     5,
		"Transformers":                  7,
		"Pirates of the Caribbean":      5,
		"The Chronicles of Narnia":      3,
		"Bourne":                        5,
		"Ocean":                         4,
		"Madagascar":                    4,
		"Kung Fu Panda":                 4,
		"How to Train Your Dragon":      3,
		"Shrek":                         5,
		"Despicable Me":                 4,
		"Minions":                       3,
		"Ice Age":                       6,
		"Jurassic World":                3,
		"Alien":                         8,
		"Predator":                      7,
		"Planet of the Apes":            10,
		"The Equalizer":                 3,
		"Taken":                         3,
		"Jack Reacher":                  2,
		"Kingsman":                      3,
		"Now You See Me":                3,
		"Fantastic Four":                5,
		"Singham":                       3,
		"Dhoom":                         3,
		"Golmaal":                       5,
		"Housefull":                     4,
		"Hera Pheri":                    3,
		"Krrish":                        4,
		"Race":                          3,
		"Dabangg":                       3,
		"Bhool Bhulaiyaa":               3,
		"Welcome":                       3,
		"Masti":                         3,
		"Baaghi":                        3,
		"Raaz":                          4,
		"Sarkar":                        3,
		"Bhoot":                         3,
		"Dhamaal":                       3,
		"Don":                           3,
		"Koi Mil Gaya":                  3,
		"Munna Bhai":                    3,
		"Pushpa":                        3,
		"KGF":                           3,
		"Baahubali":                     3,
		"Drishyam":                      3,
		"Stree":                         3,
		"Aashiqui":                      3,
		"Student of the Year":           2,
		"Badrinath Ki Dulhania":         2,
		"Hum Saath Saath Hain":          2,
		"Yamla Pagla Deewana":           3,
		"Tanu Weds Manu":                2,
		"Lage Raho":                     2,
		"Vikram Vedha":                  2,
		"Chashme Baddoor":               2,
		"Mardaani":                      3,
		"Fukrey":                        3,
		"Dream Girl":                    2,
		"Bunty Aur Babli":               2,
		"Special 26":                    2,
		"The Expendables":               4,
		"The Maze Runner":               3,
		"The Meg":                       2,
		"Jumanji":                       4,
		"Paddington":                    2,
		"A Quiet Place":                 3,
		"Shazam":                        2,
		"Venom":                         3,
		"The Nun":                       2,
		"Sonic the Hedgehog":            2,
		"The Lego Movie":                4,
		"Hotel Transylvania":            4,
		"The Croods":                    2,
		"Spider Verse":                  3,
		"The Purge":                     5,
		"Annabelle":                     3,
		"James Bond":                    27,
		"Godzilla":                      38,
		"Star Trek":                     13,
		"Halloween":                     13,
		"Friday the 13th":               12,
		"A Nightmare on Elm Street":     9,
		"Hellraiser":                    11,
		"Childs Play":                   8,
		"Texas Chainsaw Massacre":       9,
		"Marvel Cinematic Universe":     35,
		"DC Extended Universe":          15,
		"Muppets":                       8,
		"Pink Panther":                  11,
		"Resident Evil":                 7,
		"Underworld":                    5,
		"Step Up":                       6,
		"American Pie":                  9,
		"Scary Movie":                   5,
		"Now Playing Classic Hollywood": 40,
		"Now Playing Classic Bollywood": 40,
	}

	pool := make([]string, 0, 3000)
	pool = append(pool, base...)
	for name, count := range franchises {
		for i := 1; i <= count; i++ {
			pool = append(pool, fmt.Sprintf("%s %d", name, i))
		}
	}

	return pool
}
